# Generated by Django 4.1.1 on 2022-10-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AplivationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='User Name', max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
