# Generated by Django 4.1.1 on 2022-09-21 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id_project', models.UUIDField(default=uuid.uuid4, help_text='Apps creadas', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='App_Name', max_length=100)),
            ],
        ),
    ]
