# Generated by Django 4.1.1 on 2022-09-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projects_description_projects_image_projects_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
