# Generated by Django 4.1.1 on 2022-09-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_projects_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='', upload_to='home/static/images'),
        ),
    ]
