# Generated by Django 4.1.1 on 2022-09-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='img',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
