# Generated by Django 4.1.1 on 2022-09-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_projects_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='', upload_to='home/static/img'),
        ),
    ]
