# Generated by Django 4.1.1 on 2022-09-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_book_bookinstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='lasst_name',
            new_name='last_name',
        ),
    ]
